# Use Amazon Linux 2023 as base image
FROM amazonlinux:2023

# Install build dependencies
RUN yum update -y && \
    yum groupinstall -y "Development Tools" && \
    yum install -y openssl-devel perl-core pcre-devel wget zlib-devel

# Install Rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

# Create working directory
WORKDIR /app

# Copy source code
COPY ./Cargo.toml .
COPY ./src ./src

RUN cargo build --release

# Create a directory for the output
RUN mkdir -p /output && \
    cp target/release/pgdevhub /output/
